package app.repository

import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import app.beans.AgentType;
import app.beans.Condo;

// TODO normalize
// TODO generate condo list from database tables instead of a hard-coded list
@Service
class CondoRepository {
	
	private final static List STATIC_LIST = [
		'515 Liholiho Street', 
		'71 Miner Place', 
		'85 Walaka Street', 
		'Aina o Kane', 
		'aina-nalu', 
		'Alaeloa', 
		'Aloha Pualani', 
		'Andaz Residences', 
		'Auhana Kuleana', 
		'Awihi Townhouse', 
		'Bay Vista Apts', 
		'Boardwalk', 
		'Carmel Apts', 
		'Chandelier Center', 
		'Channel House', 
		'Coconut Grove', 
		'Cottages at Kulamalu', 
		'Gardens at West Maui', 
		'Gardens Upcountry', 
		'Grand Champions', 
		'Hale Hui Kai', 
		'Hale Iliili', 
		'Hale Kai I', 
		'Hale Kai O Kihei I', 
		'Hale Kai O Kihei II', 
		'Hale Kamaole', 
		'Hale Kanani', 
		'Hale Mahialani', 
		'Hale Mahina', 
		'Hale Nani', 
		'Hale Napili Apts', 
		'Hale Ono Loa', 
		'Hale Pau Hana', 
		'Hale Royale', 
		'Hale Wailana', 
		'Haleakala Gardens', 
		'Haleakala Shores', 
		'Hana Kai-Maui', 
		'Happy Valley Village', 
		'Harbor Lights', 
		'Hawealani Condominium', 
		'Hokulani Golf Villas', 
		'Hololani', 
		'Hono Kai', 
		'Hono Koa', 
		'Honokeana Cove', 
		'Honokowai East', 
		'Honokowai Palms', 
		'Honua Kai - Hoku Lani', 
		'Honua Kai - Konea', 
		'Hoolea Terrace at Kehalani', 
		'Hoolei', 
		'Hotel Hana-Maui Condominiums', 
		'Hotel Molokai', 
		'Hoyochi Nikko', 
		'Iao Gardens', 
		'Iao Parkside I', 
		'Iao Parkside II', 
		'Iao Parkside III', 
		'Iao Parkside IV-A', 
		'Iao Parkside IV-B', 
		'Iao Parkside IV-C', 
		'Iliahi at Kehalani', 
		'International Colony Club I', 
		'International Colony Club II', 
		'Island Sands', 
		'Island Surf', 
		'Kaanapali Alii', 
		'Kaanapali Beach Club', 
		'Kaanapali Beach Vacation Resort', 
		'Kaanapali Plantation', 
		'Kaanapali Royal', 
		'Kaanapali Shores', 
		'Kahana Beach Resort', 
		'Kahana Falls', 
		'Kahana Manor', 
		'Kahana Outrigger', 
		'Kahana Reef', 
		'Kahana Sunset', 
		'Kahana Villa', 
		'Kahana Village', 
		'Kahekili Grove', 
		'Kahului Ikena', 
		'Kai Ani Village', 
		'Kai Makani', 
		'Kai Malu', 
		'Kalama Gardens', 
		'Kalama Kai',
		'Kalama Terrace', 
		'Kalama Townhouses', 
		'Kalama Villa', 
		'Kaleialoha', 
		'Kamaole Beach Club', 
		'Kamaole Beach Royale', 
		'Kamaole Nalu', 
		'Kamaole One', 
		'Kamaole Sands', 
		'Kamoa Views', 
		'Kanai A Nalu', 
		'Kanani Wailea', 
		'Kane', 
		'Kanoe Apts', 
		'Kanoe Palms', 
		'Kanoelani Apts', 
		'Kapalua Bay Villas I', 
		'Kapalua Bay Villas II', 
		'Kapalua Golf Villas', 
		'Kapalua Ironwoods', 
		'Kapalua Ridge', 
		'Kapu Townhouses', 
		'Kauhale Makai', 
		'Ke Alii Ocean Villas', 
		'Ke Nani Kai', 
		'Kealaloa Court', 
		'Kealia', 
		'Keala O Wailea',
		'Keawakapu', 
		'Kehalani Gardens', 
		'Keonekai Villages', 
		'Kihei Akahi', 
		'Kihei Alii Kai', 
		'Kihei Bay Surf', 
		'Kihei Bay Vista', 
		'Kihei Beach', 
		'Kihei Cove', 
		'Kihei Garden Estates', 
		'Kihei Holiday', 
		'Kihei Islana', 
		'Kihei Kai', 
		'Kihei Kai Nani', 
		'Kihei Manor', 
		'Kihei Pacific Plaza', 
		'Kihei Palms', 
		'Kihei Parkshore', 
		'Kihei Resort', 
		'Kihei Sands', 
		'Kihei Shores', 
		'Kihei Surfside', 
		'Kihei View Apts', 
		'Kihei Villa', 
		'Kihei Villages I', 
		'Kihei Villages II', 
		'Kihei Villages III', 
		'Kihei Villages IV', 
		'Kihei Villages V', 
		'Kihei Villages VI', 
		'Kipa Village', 
		'Koa Kai', 
		'Koa Lagoon', 
		'Koa Resort', 
		'Kuau Plaza', 
		'Kulakane', 
		'Kulaview', 
		'Kuleana I', 
		'Kuleana II', 
		'Lahaina Residential', 
		'Lahaina Roads', 
		'Lahaina Shores', 
		'Lanai City Apartments', 
		'Lanakila', 
		'Laulea', 
		'Laulima Lane', 
		'Lauloa', 
		'Leilani Kai', 
		'Leinaala', 
		'Leinani Apts', 
		'Lokahi', 
		'Loke Hale', 
		'Lokelani', 
		'Luana Kai', 
		'Maalaea Banyans', 
		'Maalaea Kai', 
		'Maalaea Mermaid', 
		'Maalaea Surf', 
		'Maalaea Yacht Marina', 
		'Mahana', 
		'Mahina Surf', 
		'Mahinahina Beach', 
		'Makalii at Wailea',
		'Makani A Kai', 
		'Makani Sands', 
		'Makena Place', 
		'Makena Sunset', 
		'Makena Surf', 
		'Mana Kai', 
		'Masters', 
		'Maui Banyan', 
		'Maui Beach Club', 
		'Maui Beachfront Resort', 
		'Maui Eldorado I', 
		'Maui Eldorado II', 
		'Maui Gardens', 
		'Maui Hill', 
		'Maui Isana Resort', 
		'Maui Kaanapali Villas', 
		'Maui Kai', 
		'Maui Kamaole', 
		'Maui Lani Terraces', 
		'Maui Ocean Club, Lahaina Tower', 
		'Maui Parkshore', 
		'Maui Realty Suites', 
		'Maui Sands I', 
		'Maui Sands II', 
		'Maui Sunset', 
		'Maui View Villas', 
		'Maui Vista', 
		'Mauian Hotel', 
		'Menehune Shores', 
		'Milowai', 
		'Miranda', 
		'Molokai Beach Cottages', 
		'Molokai Shores', 
		'Montage Residences Kapalua Bay', 
		'Mount Thomas', 
		'Na Hale O Makena', 
		'Na Holokai', 
		'Nani Kai Hale', 
		'Napili Bay', 
		'Napili Gardens', 
		'Napili Lani', 
		'Napili Point I', 
		'Napili Point II', 
		'Napili Puamala', 
		'Napili Ridge', 
		'Napili Shores', 
		'Napili Sunset', 
		'Napili Surf', 
		'Napili Village', 
		'Napili Villas', 
		'Napilihau Villages I', 
		'Noelani', 
		'Nohonani', 
		'One Konou Place', 
		'One Napili Way', 
		'Opukea at Lahaina', 
		'Pacific Shores', 
		'Paki Maui I II', 
		'Paki Maui III', 
		'Palms at Manele I', 
		'Palms at Wailea I', 
		'Paniolo Country Estates', 
		'Paniolo Hale', 
		'Papakea Resort I II', 
		'Papali Wailea', 
		'Parkview Square', 
		'Pikake', 
		'Pines at Koele', 
		'Pires Place', 
		'Pohailani Maui', 
		'Poinciana Place', 
		'Polo Beach Club', 
		'Polynesian Shores', 
		'Puamana', 
		'Puna II', 
		'Puna Point I', 
		'Punahoa Beach Apts', 
		'Puunoa Beach Estates', 
		'Puuone Gardens', 
		'Puuone Hale Alii', 
		'Puuone Terrace', 
		'Puuone Towers and Plaza', 
		'Royal Kahana', 
		'Royal Maui Kai', 
		'Royal Mauian', 
		'Royal Menehune', 
		'Sands of Kahana', 
		'Shores of Maui', 
		'Southpointe at Waiakoa', 
		'Spinnaker', 
		'Sugar Beach Resort', 
		'Sugar Cove', 
		'Terraces Manele Bay I', 
		'Terraces Manele Bay II', 
		'Terraces Manele Bay III', 
		'Terraces Manele Bay IV', 
		'Terraces Manele Bay V', 
		'The Breakers', 
		'The Ritz Hotel Suites', 
		'The Ritz Carlton Residences',
		'The Suites at Wailea', 
		'Uluniu Townhouse', 
		'US Duplex', 
		'Valley Isle Resort', 
		'Villas at Kahana Ridge', 
		'Villas at Kehalani', 
		'Villas at Kenolio I', 
		'Villas at Kenolio II', 
		'Villas at Koele I', 
		'Villas at Koele II', 
		'Vintage at Kaanapali', 
		'Wailana Kai', 
		'Wailana Sands', 
		'Wailea Beach Villas', 
		'Wailea Ekahi I', 
		'Wailea Ekahi II', 
		'Wailea Ekahi III', 
		'Wailea Ekolu', 
		'Wailea Elua I A', 
		'Wailea Elua I B', 
		'Wailea Elua II', 
		'Wailea Fairway Villas', 
		'Wailea Palms', 
		'Wailea Point I II III', 
		'Wailea Town Center', 
		'Wailuku Manor', 
		'Wailuku Townhouses', 
		'Waiohuli Beach Duplex', 
		'Waiohuli Beach Hale', 
		'Waipuilani', 
		'Walaka Apartments', 
		'Walaka Maui', 
		'Wavecrest', 
		'Wells St Prof Center', 
		'West Maui Trades', 
		'West Molokai Resort', 
		'Whaler I', 
		'Whaler II', 
		'White Sea Terrace', 
		'_Residential House', 
		'_Vacant Land'
	];

//	private final static String LIST_CONDO_SQL ="SELECT distinct BuildingName as name FROM Property order by BuildingName";
//	
//
//	@Autowired
//	private JdbcTemplate jdbcTemplate;
//	
//	private List cache = [];
//	
//	@PostConstruct
//	public init () {
//		cache = jdbcTemplate.queryForList(LIST_CONDO_SQL);
//		cache.flatten
//		println cache
//	}
//	
//	public Condo findCondo (Object id) {
//		return cache.get(id);
//	}

	public List<Condo> listCondos () {
		List condos = [];
		int i=0;
		for (def c : STATIC_LIST) {
			Condo condo = new Condo();
			condo.setId(i++);
			condo.setName(c);
			condos.add(condo);
		}
		return condos;
	}
	
}
