package app.service.odata
/*
@odata.type: "#RAMOdata.Models.Condo",
Status: "ACTIVE",
StatusCategory: "Active",
PropertyType: "Condo",
ListPrice: 1425000,
MLSNumber: 329222,
TMK: "2420010240121",
Address: "500 Bay DR",
District: "Kapalua",
DOM: 2489,
ListDate: "2008-01-19",
LandAcres: "16.4",
LandSqFt: 0,
View: "Ocean",
REO: false,
PotentialShortSale: false,
Waterfront: "OceanFront",
LandTenure: "FeeSimple",
MaintenanceFee: 0,
Longitude: "-156.662658691406",
Latitude: "21.0029144287109",
ListingAgentFirstName: "Patrick",
ListingAgentLastName: "Sullivan",
ListingAgent1Email: "Pat@SullivanProperties.com",
ListingAgent1Phone: "8706428",
ListingAgent1PhoneArea: "808",
ListingAgent1Phone2: "",
ListingAgent1Phone2Area: "",
ListingAgent1Url: "www.SullivanProperties.com",
ListingAgent2FirstName: "",
ListingAgent2LastName: "",
ListingAgent2Email: "",
ListingAgent2Phone: "",
ListingAgent2PhoneArea: "",
ListingAgent2Phone2: "",
ListingAgent2Phone2Area: "",
ListingAgent2Url: "",
ListingOffice1Email: "info@SullivanProperties.com",
ListingOffice1Name: "Sullivan Properties Inc",
ListingOffice1Phone: "6690423",
ListingOffice1PhoneArea: "808",
ListingOffice1Url: "www.SullivanProperties.com",
ListingOffice2Email: "",
ListingOffice2Name: "",
ListingOffice2Phone: "",
ListingOffice2PhoneArea: "",
ListingOffice2Url: "",
Baths: 1,
Beds: 1,
Pool: true,
LivingAreaSqFt: 1006,
PVInstalled: false,
Unit: "34-B4",
BuildingName: "Kapalua Bay Villas II"
}
 */
class Mappings {
	final static String maping= '''

{
  "mappings": {
    "MLS": "MLSNumber",
    "Class": 2, 
    "Type": "PropertyType",
    "District": "District",
    "ListPrice": "ListPrice",
    "AddressNumber": 8,
    "AddressDirection": 7,
    "AddressStreet": "Address",
    "AddressLotUnit": 9,
    "City": 10,
    "State": 11,
    "Zip": 12,
    "Status": "Status",
    "WaterFront": "Waterfront",
    "View": "View",
    "AgentID": 16,
    "AgentName": "ListingAgent1FullName",
    //"AgentPhone": ["ListingAgent1PhoneArea", "ListingAgent1Phone", "ListingAgent1Phone2Area", "ListingAgent1Phone2"],
    "AgentPhone": ["ListingAgent1PhoneArea", "ListingAgent1Phone"],
    "ListingOffice1_ID": 19,
    "ListingOffice1_Name": "ListingOffice1Name",
    "ListingOffice1_Phone": ["ListingOffice1PhoneArea","ListingOffice1Phone"],
    "CoListingAgent_ID": 22,
    "CoListingAgent_Name": "ListingAgent2FullName",
   // "CoListingAgent_Phone": ["ListingAgent2PhoneArea","ListingAgent2Phone","ListingAgent2Phone2Area","ListingAgent2Phone2"],
    "CoListingAgent_Phone": ["ListingAgent2PhoneArea","ListingAgent2Phone"],
    "ListingOffice2_ID": 25,
    "ListingOffice2_Name": "ListingOffice2Name",
    "ListingOffice2_Phone": ["ListingOffice2PhoneArea", "ListingOffice2Phone"],
    "ListDate": "ListDate",
    "VirtualTour": 29,
    "Div": 30,
    "Zone": 31,
    "Sec": 32,
    "Plat": 33,
    "Par": 34,
    "Unit": 35,
    "CPR": 36,
    "HouseCarport": "CarportNumCars",
    "HouseGarage": "GarageNumCars",
    "LT": "LandTenure",
    "PartialOwnership": 42,
    "PercentOwnership": 43,
    "BuildingName": "BuildingName",
    "FloorLevel": 45,
    "Beds": "Beds",
    "Baths": "Baths",
    "LivSQFT": "LivingAreaSqFt",
    "LandSQFT": "LandSqFt",
    "LandAcres": "LandAcres",
    "MaintFee": "MaintenanceFee",
    "PublicRemarks": 52,
    "Ohana_Beds": "OhanaBeds",
    "Ohana_Baths": "OhanaBaths",
    "Ohana_LivSQFT": "OhanaSqFt",
    "OhanaCarport": "OhanaCarportNumCars",
    "OhanaGarage": "OhanaGarageNumCars",
    "FixedBeginDate": 56,
    "FixedEndDate": 57,
    "Res_Condo": 58,
    "VOWAddress": 59,
    "VOWComment": 60,
    "VOWAVM": 61,
    "VOWInclude": 62,
    "PotentialShortSale": "PotentialShortSale",
    "REO": "REO",
    "AgentEmail": "ListingAgent1Email",
    "AgentFax": 66,
    "AgentWebPage": "ListingAgent1Url",
    "AgentFullName": 68,//ListingAgentLastName 
    "ListingOffice1_Email": "ListingOffice1Email",
    "ListingOffice1_Fax": 70,
    "ListingOffice1_WebPage": 71,
    "CoListingAgent_Email": 72,
    "CoListingAgent_Fax": 73,
    "CoListingAgent_WebPage": 74,
    "CoListingAgent_FullName": 75,
    "ListingOffice2_Email": 76,
    "ListingOffice2_Fax": 77,
    "ListingOffice2_WebPage": 78,
    "Lat": "Latitude",
    "Lon": "Longitude",
    "PoolYN": "Pool",
    "PV_Installed": "PVInstalled",
    "PVO_Installed": 83,
    "PV_Ownership": 84,
    "PVO_Ownership": 85,
    "Images": 86
  }
}
'''
}
